### ISSUE TITLE
Failed jobs in queue manager

### ISSUE THREAD

**Issue by anita-chouhan** [mmikkel/CacheFlag-Craft3#21]
## **Bug Description**

**Description**

I am getting a failed job in the queue manager on deleting an entry. The entry contains a *Neo* field with multiple blocks in it.

**Other information**

I [reported the bug](https://github.com/spicywebau/craft-neo/issues/724) to the *Neo* plugin author and after analysing the files for my project setup he concluded that there is a conflict with the *Cache Flag plugin.*

Here is the log:
```
2023-04-14 12:50:58 [-][1][-][error][craft\queue\QueueLogBehavior::afterError]  [334] Deleting old Neo blocks (attempt: 1, pid: 2328) - Error (time: 0.007s): Invalid owner ID: 35277
2023-04-14 12:50:58 [-][1][-][error][yii\base\InvalidConfigException] yii\base\InvalidConfigException: Invalid owner ID: 35277 in /var/www/html/vendor/spicyweb/craft-neo/src/elements/Block.php:347
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/helpers/ElementHelper.php(414): benf\neo\elements\Block->getOwner()
#1 /var/www/html/vendor/craftcms/cms/src/helpers/ElementHelper.php(452): craft\helpers\ElementHelper::rootElement(Object(benf\neo\elements\Block))
#2 /var/www/html/vendor/mmikkel/cache-flag/src/CacheFlag.php(226): craft\helpers\ElementHelper::isDraftOrRevision(Object(benf\neo\elements\Block))
#3 /var/www/html/vendor/mmikkel/cache-flag/src/CacheFlag.php(180): mmikkel\cacheflag\CacheFlag->_maybeInvalidateFlaggedCachesByElement(Object(benf\neo\elements\Block))
#4 [internal function]: mmikkel\cacheflag\CacheFlag->mmikkel\cacheflag\{closure}(Object(craft\events\DeleteElementEvent))
#5 /var/www/html/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\events\DeleteElementEvent))
#6 /var/www/html/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger('craft\\services\\...', 'beforeDeleteEle...', Object(craft\events\DeleteElementEvent))
#7 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(1699): yii\base\Component->trigger('beforeDeleteEle...', Object(craft\events\DeleteElementEvent))
#8 /var/www/html/vendor/spicyweb/craft-neo/src/jobs/DeleteBlock.php(49): craft\services\Elements->deleteElement(Object(benf\neo\elements\Block), false)
#9 /var/www/html/vendor/yiisoft/yii2-queue/src/Queue.php(246): benf\neo\jobs\DeleteBlock->execute(Object(craft\queue\Queue))
#10 /var/www/html/vendor/yiisoft/yii2-queue/src/cli/Queue.php(147): yii\queue\Queue->handleMessage('334', 'O:25:"benf\\neo\\...', '300', 1)
#11 /var/www/html/vendor/craftcms/cms/src/queue/Queue.php(131): yii\queue\cli\Queue->handleMessage('334', 'O:25:"benf\\neo\\...', '300', 1)
#12 [internal function]: craft\queue\Queue->craft\queue\{closure}(Object(Closure))
#13 /var/www/html/vendor/yiisoft/yii2-queue/src/cli/Queue.php(117): call_user_func(Object(Closure), Object(Closure))
#14 /var/www/html/vendor/craftcms/cms/src/queue/Queue.php(140): yii\queue\cli\Queue->runWorker(Object(Closure))
#15 /var/www/html/vendor/craftcms/cms/src/controllers/QueueController.php(84): craft\queue\Queue->run()
#16 [internal function]: craft\controllers\QueueController->actionRun()
#17 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#18 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#19 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('run', Array)
#20 /var/www/html/vendor/craftcms/cms/src/web/Application.php(293): yii\base\Module->runAction('queue/run', Array)
#21 /var/www/html/vendor/craftcms/cms/src/web/Application.php(602): craft\web\Application->runAction('queue/run', Array)
#22 /var/www/html/vendor/craftcms/cms/src/web/Application.php(272): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#23 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#24 /var/www/html/web/index.php(26): yii\base\Application->run()
#25 {main}
```

Can you kindly look into it and suggest a way to resolve this issue?

For more details, please check: [https://github.com/spicywebau/craft-neo/issues/724](https://github.com/spicywebau/craft-neo/issues/724)

**Steps to reproduce**

1. Install and enable *Neo* and *Cache Flag* plugins.
2. Add an entry with a *Neo* field with multiple blocks in it.
3. Try to delete the saved entry.

**Expected behaviour**

The entry should delete properly without any failed job.

**Neo version**

2.13.16

**Cache Flag version**

1.3.3

**Craft CMS version**

3.8.2

**Comment by mmikkel** [comment]
Thanks for reporting that. In my opinion this is a Neo issue, and I've made a comment on https://github.com/spicywebau/craft-neo/issues/724 explaining why.

That said, the problem is easy enough to mitigate in Cache Flag, and I've just published v. 1.3.4 which should resolve the issue.

**Comment by anita-chouhan** [comment]
Thank you for looking into it and providing an update.
